name: Release Lawnchair module

on:
  workflow_dispatch:
    branches:
      - Origin

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Remove .github and .git folders
      run: |
        find . -type d -name .github -exec rm -rf {} +
        rm -rf .git
    
    - name: Upload files
      uses: actions/upload-artifact@v4
      with:
        name: Lawnchairmodule_dev
        path: ./
        if-no-files-found: error
